// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// <auto-generated />
using AnniversaryBirthdayReminder.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnniversaryBirthdayReminder.Infrastructure.Migrations;

[DbContext(typeof(AnniversaryBirthdayReminderContext))]
[Migration("20241229000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("AnniversaryBirthdayReminder.Core.Celebration", b =>
            {
                b.Property<Guid>("CelebrationId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Attendees")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CelebrationDate")
                    .HasColumnType("datetime2");

                b.Property<Guid>("ImportantDateId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Notes")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<string>("Photos")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("Rating")
                    .HasColumnType("int");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("CelebrationId");

                b.HasIndex("CelebrationDate");

                b.HasIndex("ImportantDateId");

                b.HasIndex("Status");

                b.ToTable("Celebrations", (string)null);
            });

        modelBuilder.Entity("AnniversaryBirthdayReminder.Core.Gift", b =>
            {
                b.Property<Guid>("GiftId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal?>("ActualPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime?>("DeliveredAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<decimal>("EstimatedPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<Guid>("ImportantDateId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("PurchasedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("PurchaseUrl")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("GiftId");

                b.HasIndex("ImportantDateId");

                b.HasIndex("Status");

                b.ToTable("Gifts", (string)null);
            });

        modelBuilder.Entity("AnniversaryBirthdayReminder.Core.ImportantDate", b =>
            {
                b.Property<Guid>("ImportantDateId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("DateType")
                    .HasColumnType("int");

                b.Property<DateTime>("DateValue")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("Notes")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("PersonName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("RecurrencePattern")
                    .HasColumnType("int");

                b.Property<string>("Relationship")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("ImportantDateId");

                b.HasIndex("DateValue");

                b.HasIndex("UserId");

                b.HasIndex("UserId", "IsActive");

                b.ToTable("ImportantDates", (string)null);
            });

        modelBuilder.Entity("AnniversaryBirthdayReminder.Core.Reminder", b =>
            {
                b.Property<Guid>("ReminderId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AdvanceNoticeDays")
                    .HasColumnType("int");

                b.Property<int>("DeliveryChannel")
                    .HasColumnType("int");

                b.Property<Guid>("ImportantDateId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("ScheduledTime")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("SentAt")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("ReminderId");

                b.HasIndex("ImportantDateId");

                b.HasIndex("ScheduledTime");

                b.HasIndex("Status");

                b.ToTable("Reminders", (string)null);
            });

        modelBuilder.Entity("AnniversaryBirthdayReminder.Core.Celebration", b =>
            {
                b.HasOne("AnniversaryBirthdayReminder.Core.ImportantDate", "ImportantDate")
                    .WithMany("Celebrations")
                    .HasForeignKey("ImportantDateId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ImportantDate");
            });

        modelBuilder.Entity("AnniversaryBirthdayReminder.Core.Gift", b =>
            {
                b.HasOne("AnniversaryBirthdayReminder.Core.ImportantDate", "ImportantDate")
                    .WithMany("Gifts")
                    .HasForeignKey("ImportantDateId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ImportantDate");
            });

        modelBuilder.Entity("AnniversaryBirthdayReminder.Core.Reminder", b =>
            {
                b.HasOne("AnniversaryBirthdayReminder.Core.ImportantDate", "ImportantDate")
                    .WithMany("Reminders")
                    .HasForeignKey("ImportantDateId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ImportantDate");
            });

        modelBuilder.Entity("AnniversaryBirthdayReminder.Core.ImportantDate", b =>
            {
                b.Navigation("Celebrations");

                b.Navigation("Gifts");

                b.Navigation("Reminders");
            });
#pragma warning restore 612, 618
    }
}
