@startsalt Neighborhood Feed
{
  {* Neighborhood Network | My Profile | Settings }
  ==
  <b>Neighborhood Feed
  ==
  {
    {
      <b>Block Party - Summer Kickoff
      Saturday, June 10 at 4:00 PM
      Maple Street (closed to traffic)
      --
      [RSVP] | 24 neighbors attending
    }
    --
    {
      <b>Safety Alert
      Suspicious activity reported on Oak Ave
      Posted 2 hours ago
      --
      [View Details]
    }
    --
    {
      <b>Help Request
      Need help moving furniture tomorrow
      Posted by neighbor 3 houses away
      --
      [Offer Help]
    }
  }
}
@endsalt
