// <auto-generated />
using System;
using DateNightIdeaGenerator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateNightIdeaGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(DateNightIdeaGeneratorContext))]
    partial class DateNightIdeaGeneratorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DateNightIdeaGenerator.Core.DateIdea", b =>
                {
                    b.Property<Guid>("DateIdeaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BudgetRange")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("HasBeenTried")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Season")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DateIdeaId");

                    b.HasIndex("BudgetRange");

                    b.HasIndex("Category");

                    b.HasIndex("HasBeenTried");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("UserId");

                    b.ToTable("DateIdeas", (string)null);
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DateIdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExperienceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photos")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.Property<bool>("WouldRepeat")
                        .HasColumnType("bit");

                    b.HasKey("ExperienceId");

                    b.HasIndex("DateIdeaId");

                    b.HasIndex("ExperienceDate");

                    b.HasIndex("UserId");

                    b.HasIndex("WasSuccessful");

                    b.ToTable("Experiences", (string)null);
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.Model.UserAggregate.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.Model.UserAggregate.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.Model.UserAggregate.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.Rating", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DateIdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DateIdeaId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExperienceId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Review")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RatingId");

                    b.HasIndex("DateIdeaId");

                    b.HasIndex("DateIdeaId1");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("ExperienceId1");

                    b.HasIndex("Score");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings", (string)null);
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.Experience", b =>
                {
                    b.HasOne("DateNightIdeaGenerator.Core.DateIdea", "DateIdea")
                        .WithMany("Experiences")
                        .HasForeignKey("DateIdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DateIdea");
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.Model.UserAggregate.Entities.UserRole", b =>
                {
                    b.HasOne("DateNightIdeaGenerator.Core.Model.UserAggregate.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.Rating", b =>
                {
                    b.HasOne("DateNightIdeaGenerator.Core.DateIdea", null)
                        .WithMany()
                        .HasForeignKey("DateIdeaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DateNightIdeaGenerator.Core.DateIdea", "DateIdea")
                        .WithMany("Ratings")
                        .HasForeignKey("DateIdeaId1");

                    b.HasOne("DateNightIdeaGenerator.Core.Experience", null)
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DateNightIdeaGenerator.Core.Experience", "Experience")
                        .WithMany("Ratings")
                        .HasForeignKey("ExperienceId1");

                    b.Navigation("DateIdea");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.DateIdea", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.Experience", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("DateNightIdeaGenerator.Core.Model.UserAggregate.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
